#!/bin/bash

arguments=()
while [ "$#" -gt 0  ]; do
    case "$1" in
        --with-argument)
            if [ "$#" -lt 2  ]; then
                echo "missing argument for option $1" >&2
                exit 4
            fi
            echo "$1 $2"
            shift
            ;;
        --long1|--long2)
            echo "long option ${1:2} met"
            ;;
        -k|-u|-i)
            echo "flag ${1:1} met"
            ;;
        --)
            shift
            arguments+=("$@")
            set --
            break;
            ;;
        --*)
            echo "Unknown long option $1" >&2
            exit 3
            ;;
        -*)
            if [ "${#1}" -eq 1 ]; then
                echo "Invalid token -" >&2
                exit 1
            fi
            if [ "${#1}" -eq 2 ]; then
                echo "unknown option $1" >&2
                exit 2
            fi
            first=${1:1:1}
            rest=${1:2}
            shift
            set -- -"$first" -"$rest" "$@"
            continue
            ;;
        *)
            arguments+=("$1")
            ;;
    esac
    shift
done

set -- "${arguments[@]}"

printf "Running with arguments: "
printf "%s, " "$@"
printf "\n"
