#!/bin/bash

arguments=()
while [ "$#" -gt 0  ]; do
    doshift=true
    case "$1" in
        -h|--help)
            echo help
            exit
            ;;
        --)
            shift
            arguments+=("$@")
            set --
            break;
            ;;
        -*)
            if [ "${#1}" -eq 1 ]; then
                echo "Invalid token -" >&2
                exit 1
            fi
            if [ "${#1}" -eq 2 ]; then
                echo "unknown option $1" >&2
                exit 2
            fi
            first=${1:1:1}
            rest=${1:2}
            shift
            set -- -"$first" -"$rest" "$@"
            doshift=false
            ;;
        *)
            echo "adding argument $1 to pool"
            arguments+=("$1")
            ;;
    esac
    if "$doshift"; then 
        shift;
    fi
done
